# Generated by Django 3.2.25 on 2024-10-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('stock_quantity', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
