# Generated by Django 3.2.25 on 2024-09-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraorderSub',
            fields=[
                ('extraordersub_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('stock_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'extraorder_sub',
                'managed': False,
            },
        ),
    ]
