# Generated by Django 3.2.25 on 2024-09-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('mess_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('department', models.CharField(db_column='Department', max_length=10)),
                ('joining_date', models.DateField()),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
