# Generated by Django 3.2.25 on 2024-10-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessBill',
            fields=[
                ('messbill_id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_date', models.DateField()),
                ('mess_id', models.IntegerField()),
                ('mess_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'mess_bill',
                'managed': False,
            },
        ),
    ]
