# Generated by Django 3.2.25 on 2024-09-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessBill',
            fields=[
                ('messbill_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('year', models.DateField()),
                ('date', models.DateField()),
                ('mess_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=45)),
                ('mess_amount', models.IntegerField()),
                ('extra_amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'mess_bill',
                'managed': False,
            },
        ),
    ]
