# Generated by Django 3.2.25 on 2024-09-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('menu_item', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('menu_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
    ]
