# Generated by Django 3.2.25 on 2024-10-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraorderMaster',
            fields=[
                ('order_id', models.AutoField(db_column='order id', primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'extraorder_master',
                'managed': False,
            },
        ),
    ]
