# Generated by Django 3.2.25 on 2024-09-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'leave_request',
                'managed': False,
            },
        ),
    ]
