# Generated by Django 3.2.25 on 2024-09-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessAmount',
            fields=[
                ('messamount_id', models.AutoField(primary_key=True, serialize=False)),
                ('daily_amount', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'mess_amount',
                'managed': False,
            },
        ),
    ]
